name: pododo-server deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Spring Boot Project
        run: ./gradlew clean build

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/gcp_ssh_key
          chmod 600 ~/.ssh/gcp_ssh_key

      - name: Upload JAR to GCP
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/gcp_ssh_key build/libs/pododo-server.jar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/${{ secrets.SERVER_USER }}/pododo-server.jar

      - name: pododo-server deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: /home/${{ secrets.SERVER_USER }}/pododo/pododo-server.sh
